### ISSUE TITLE
userObj is null for some users.

### ISSUE THREAD

**Issue by tdhz77** [JackAdams/meteor-accounts-ldap#10]
Our ldap works for some users but not all! Do you know any reason why this might be?

Thank you!

I20160105-12:21:46.356(-6)? No result found.
I20160105-12:21:46.356(-6)? status: 0
I20160105-12:21:46.454(-6)? Exception while invoking method 'login' TypeError: Cannot read property 'userObj' of null
I20160105-12:21:46.454(-6)?     at [object Object].Package (packages/babrahams_accounts-ldap/ldap_server.js:295:1)
I20160105-12:21:46.454(-6)?     at accounts_server.js:462:32
I20160105-12:21:46.454(-6)?     at tryLoginMethod (accounts_server.js:239:14)
I20160105-12:21:46.455(-6)?     at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
I20160105-12:21:46.455(-6)?     at [object Object].methods.login (accounts_server.js:522:27)
I20160105-12:21:46.455(-6)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160105-12:21:46.455(-6)?     at livedata_server.js:708:19
I20160105-12:21:46.455(-6)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160105-12:21:46.455(-6)?     at livedata_server.js:706:40
I20160105-12:21:46.455(-6)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

**Comment by JackAdams** [comment]
[This line](https://github.com/JackAdams/meteor-accounts-ldap/blob/master/ldap_server.js#L120) is the problem.  I'm going to add a way to overwrite this default so that you can target the correct field when searching for users.

**Comment by tdhz77** [comment]
LDAP.filter = function (isEmailAddress, usernameOrEmail) {
  return '(&(cn=' + ((isEmailAddress) ? usernameOrEmail.split('@')[0] : usernameOrEmail) + ')(objectClass=user))';
}

Does this not already do such?

**Comment by JackAdams** [comment]
That's for the search part.  There's no equivalent function for the bind.  Thanks for raising this issue -- I've been meaning to add this flexibility for a while.

**Comment by tdhz77** [comment]
@JackAdams I'm pretty lost at the moment. Some of our users are in the same OU as others and cannot login ( the userObj returns null. ) so, how does this change solve this problem?

I don't think I'm understanding. Also, while I can return fields like displayName, I'm unable to return mail or zipcode fields. 

I have both fields whitelisted.. here is an example of a successful login via json.


        {
           "dn":"CN=JBROWN,OU=Automation Computers,OU=Automation,OU=WRA,DC=winad,DC=sub,DC=google,DC=com",
           "controls":[

           ],
           "objectClass":[
              "top",
              "person",
              "organizationalPerson",
              "user",
              "computer"
           ],
           "cn":"JBROWN",
           "distinguishedName":"CN=JBROWN,OU=Automation Computers,OU=Automation,OU=WRA,DC=winad,DC=sub,DC=google,DC=com",
           "instanceType":"4",
           "whenCreated":"20140910142758.0Z",
           "whenChanged":"20141121142347.0Z",
           "displayName":"JBROWN$",
           "uSNCreated":"19000385",
           "uSNChanged":"19815938",
           "name":"JBROWN",
           "objectGUID":"�\u0000\u0000ҥ\u0011�M�\"Y�\u0005�\u001d�",
           "userAccountControl":"4096",
           "badPwdCount":"0",
           "codePage":"0",
           "countryCode":"0",
           "badPasswordTime":"0",
           "lastLogoff":"0",
           "lastLogon":"130614848969858152",
           "localPolicyFlags":"0",
           "pwdLastSet":"130602773328058347",
           "primaryGroupID":"515",
           "objectSid":"\u0001\u0005\u0000\u0000\u0000\u0000\u0000\u0005\u0015\u0000\u0000\u0000ƻPzWf�b#_ck[Z\u0000\u0000",
           "accountExpires":"9223372036854775807",
           "logonCount":"259",
           "sAMAccountName":"JBROWN$",
           "sAMAccountType":"805306369",
           "operatingSystem":"Windows 7 Professional",
           "operatingSystemVersion":"6.1 (7601)",
           "operatingSystemServicePack":"Service Pack 1",
           "dNSHostName":"JBROWN.winad.sub.google.com",
           "servicePrincipalName":[
              "RestrictedKrbHost/JBROWN.winad.sub.google.com",
              "HOST/JBROWN.winad.sub.google.com",
              "RestrictedKrbHost/JBROWN",
              "HOST/JBROWN"
           ],
           "objectCategory":"CN=Computer,CN=Schema,CN=Configuration,DC=winad,DC=sub,DC=google,DC=com",
           "isCriticalSystemObject":"FALSE",
           "dSCorePropagationData":[
              "20140924135605.0Z",
              "16010101000001.0Z"
           ],
           "lastLogonTimestamp":"130610534272640901",
           "msDS-SupportedEncryptionTypes":"28"
        }

**Comment by JackAdams** [comment]
I'm not seeing `zipcode` or `mail` fields being returned in that user object from a successful login.  Are they in the actual record on the LDAP server?

At the moment, the bind to the LDAP server is done by using `userDn = ((email) ? username.split('@')[0] : username) + '@' + serverDn;` along the password the user supplies.  This `userDn` value is the sort of thing that would usually be found in the `userPrincipalName` field in an LDAP record (and often in the `mail` field), which currently restricts use of this package to directories that have this sort of field for all users. This is bad and needs fixing. I need to add: 1) a better default, 2) a way to overwrite this function in the same way that there is an overwriteable `LDAP.filter` function in the search part of the package.

I'm hoping to release a fix within a week or so.

**Comment by JackAdams** [comment]
Did 0.4.5 fix this issue?

**Comment by tdhz77** [comment]
I'll get back to you. I'm currently deploying.

**Comment by JackAdams** [comment]
I've got a feeling it won't actually fix the problem.  I'm having a similar problem where a small fraction of users can't log in.

**Comment by tdhz77** [comment]
No dice. {"dn":"","code":49,"name":"InvalidCredentialsError","message":"80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\u0000"}

**Comment by JackAdams** [comment]
Yeah. Same sort of problems I'm having. Hoping it'll be fixed soon. I'm using it in production and users are getting frustrated so I'm pretty motivated to solve this.

**Comment by tdhz77** [comment]
Similar boat, but with considerable less talent.

**Comment by JackAdams** [comment]
Just release 0.4.6, which fixes (at least some of) my problems but, judging by the error message, I don't think it's going to help with the problem you've described.

**Comment by tdhz77** [comment]
Yes, 0.4.6 doesn't fix it, but it doesn't break it. I'm still trying to get some time to deal with all of these. I will as soon as possible try and figure this one out.

**Comment by tdhz77** [comment]
So, if I'm understanding right -- You believe that not all of my users have the userPrincipalName?
I ran sysinternals and it appears every user has userPrincipal name with the structure firstinitial_lastname@winad.sub.google.com -- I'm struggling to understand LDAP bind I think

**Comment by JackAdams** [comment]
No, that's probably not it.  I'm struggling to understand LDAP bind too.  I'm not very knowledgeable about LDAP and active directories.  I've got customers who want this sorted out yesterday, so I'm pretty motivated to figure out the problem.  Still working on it ...

**Comment by JackAdams** [comment]
I don't see a `userPrincipalName` field in the example of a user returned from a successful bind/search.  I just learned a whole heap about LDAP tonight and I'll shortly be releasing a new version of the package that should be flexible enough to work for your AD set up.  If you can send me an example of exactly what is typed into the `Username or email` field for a successful login and the same for an unsuccessful login, I should be able to point you in the right direction to write some app code so that it works for all your users.  By the way, that dump of json from a successful login above is very helpful for seeing how your records are formatted and what is going to work for everyone.

**Comment by JackAdams** [comment]
I'm pretty sure the new release (0.5.0) will solve the problems you've been having with the package.
In your server code, put:
```
LDAP.searchField='userPrincipalName';
LDAP.searchValueType='userPrincipalName';
```
(It's now working well with the AD I'd been having trouble authenticating against.)

**Comment by tdhz77** [comment]
Fixed. Thank you. What's great is that I figured it out today without seeing this post. :) Thank you for all of your efforts. I also used sAMAccountName and it works too.
