### ISSUE TITLE
No compatible binary build....

### ISSUE THREAD

**Issue by Suppen** [JackAdams/meteor-accounts-ldap#2]
Hello

Getting this again for 0.1.4. 0.1.2 worked.

```
$ meteor add babrahams:accounts-ldap@0.1.4
 => Errors while adding packages:             

While checking for babrahams:accounts-ldap@0.1.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by JackAdams** [comment]
Yeah, sorry.  I released a new version and only managed to get one build successfully published.  I think it was the OSX one.  I'm going to release a new version and try again now.

**Comment by JackAdams** [comment]
I'm having real trouble getting the binaries published.  For the moment, it might be best to use 0.1.2.

**Comment by JackAdams** [comment]
Okay, finally got the binary builds to publish. 0.1.5 should be okay to use.
