### ISSUE TITLE
settings.json not found

### ISSUE THREAD

**Issue by tomsen-san** [JackAdams/meteor-accounts-ldap#23]
Hi there 
I created a settings.json according to the docs and placed it on the server. When trying to login I get an error saying 

```shell
=> Meteor server restarted
I20180220-10:17:14.672(1)? Exception while invoking method 'login' Error: LDAP settings missing.
I20180220-10:17:14.673(1)?     at MethodInvocation.<anonymous> (packages/babrahams_accounts-ldap.js:392:11)
I20180220-10:17:14.674(1)?     at packages/accounts-base/accounts_server.js:483:32
I20180220-10:17:14.674(1)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:259:14)
```
Where do I have to place it to be found? Or do I have to assign the value somewhere to the LDAP object?

**Comment by JackAdams** [comment]
You need to start Meteor with:
```
meteor --settings settings.json
```
(if the `settings.json` file is in the top level directory of your project) for the settings to take effect.

See the docs here:

[https://docs.meteor.com/api/core.html#Meteor-settings](https://docs.meteor.com/api/core.html#Meteor-settings)

**Comment by tomsen-san** [comment]
Ah. Something learned. :-) I do a mup deploy so ... have to place it into an environment variable which should be doable. Thanks!
