### ISSUE TITLE
Latest version 0.7.6 not available

### ISSUE THREAD

**Issue by sandrich** [JackAdams/meteor-accounts-ldap#26]
Hi

I tried to install the latest version 0.7.6 but that is apparently not available?

```
 => Errors while parsing arguments:

While adding package babrahams:accounts-ldap@0.7.6:
error: no such version babrahams:accounts-ldap@0.7.6

```

The latest I can download is **v0.7.4**

**Comment by JackAdams** [comment]
Weird. Something might have gone wrong in the publishing process. Try version 0.7.7.

**Comment by sandrich** [comment]
Mhm the problem was on my end. I cannot update the catalog through the corporate firewall. Sorry about that.
