### ISSUE TITLE
"Future resolved more than once" error

### ISSUE THREAD

**Issue by ay13** [JackAdams/meteor-accounts-ldap#3]
When i submit the form to log in it freezes at "Logging in ..." and the console has the following output.

W20150724-10:07:23.076(-5)? (STDERR) 
W20150724-10:07:23.077(-5)? (STDERR) /Users/ayoung/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:226
W20150724-10:07:23.077(-5)? (STDERR)                    throw new Error('Future resolved more than once');
W20150724-10:07:23.077(-5)? (STDERR)                          ^
W20150724-10:07:23.083(-5)? (STDERR) Error: Future resolved more than once
W20150724-10:07:23.083(-5)? (STDERR)     at Object.Future.return (/Users/ayoung/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:226:10)
W20150724-10:07:23.083(-5)? (STDERR)     at EventEmitter.<anonymous> (packages/babrahams:accounts-ldap/ldap_server.js:81:1)
W20150724-10:07:23.083(-5)? (STDERR)     at EventEmitter.emit (events.js:95:17)
W20150724-10:07:23.083(-5)? (STDERR)     at _done (/Users/ayoung/.meteor/packages/babrahams_accounts-ldap/.0.1.0.1paav43++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js:785:22)
W20150724-10:07:23.083(-5)? (STDERR)     at messageCallback (/Users/ayoung/.meteor/packages/babrahams_accounts-ldap/.0.1.0.1paav43++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js:858:14)
W20150724-10:07:23.083(-5)? (STDERR)     at Parser.onMessage (/Users/ayoung/.meteor/packages/babrahams_accounts-ldap/.0.1.0.1paav43++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js:199:12)
W20150724-10:07:23.084(-5)? (STDERR)     at Parser.emit (events.js:95:17)
W20150724-10:07:23.084(-5)? (STDERR)     at Parser.write (/Users/ayoung/.meteor/packages/babrahams_accounts-ldap/.0.1.0.1paav43++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/ldapjs/lib/messages/parser.js:105:8)
W20150724-10:07:23.084(-5)? (STDERR)     at end (/Users/ayoung/.meteor/packages/babrahams_accounts-ldap/.0.1.0.1paav43++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/ldapjs/lib/messages/parser.js:71:19)
W20150724-10:07:23.084(-5)? (STDERR)     at Parser.write (/Users/ayoung/.meteor/packages/babrahams_accounts-ldap/.0.1.0.1paav43++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/ldapjs/lib/messages/parser.js:107:10)

**Comment by JackAdams** [comment]
Yep... working on this right now.  Version 0.2.1 and 0.2.2 are problematic.  Use `babrahams:accounts-ldap@0.2.0` for the moment. Sorry!

Out of interest, does 0.2.0 work fine?

**Comment by JackAdams** [comment]
It's got me beaten.  I'm going to need some help from someone who knows more about Futures and Fibers.

**Comment by JackAdams** [comment]
This should be fixed in versions 0.3.x.  Let me know if it's not!
