### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by JackAdams** [JackAdams/meteor-accounts-ldap#4]
Happened in the 0.2.1 build and 0.2.2 build (where I was trying to fix it but failed).  Was not an issue up to and including 0.2.0.

Disappointing.

It still works, but who wants error message in the console on app startup?

**Comment by raduchiriac** [comment]
same here. Where does it come from?

**Comment by JackAdams** [comment]
I've been trying to track it down, but I'm out of my depth.  It might be something to do with changes to the build machines for npm binaries.  I'm not doing anything different when I publish the binaries, but I've noticed a structure change in the directories of the package builds in my `~/.meteor/packages/babrahams_accounts-ldap/` directory.

For the moment:

```
meteor remove babrahams:accounts-ldap
meteor add babrahams:accounts-ldap@0.2.0
```

This is really annoying me as I need to use the API extensions from `0.2.1`.  I might need to ask for help on the forums.

**Comment by JackAdams** [comment]
If the meteor binary build machines, which I have no control over, update their dtrace versions to match the node version they're running that might solve the problem.  Or if a new version of ldapjs is released with the optional dependency on dtrace removed (unlikely, given the recent activity in that repo), that would solve the problem.

I'm afraid this one isn't going away anytime soon. 

Fortunately, the package still works just fine, as dtrace is an optional dependency and has no effect on the functionality of ldapjs.  It just uglies up your server console on app startup.

**Comment by raduchiriac** [comment]
Thank you for investigating this in detail. It's true that it's only ugly and a rather harmless error.

**Comment by JackAdams** [comment]
Can finally close this with the release of v0.7.0, which uses ldapjs v.1.0.0.
