### ISSUE TITLE
unable to install package

### ISSUE THREAD

**Issue by zalewskigrzegorz** [JackAdams/meteor-accounts-ldap#6]
Hi after update meteor 
when i try to add package i got a error 

 add babrahams:accounts-ldap
 => Errors while adding packages:             

While selecting package versions:
error: Conflict: Constraint less@1.0.14 is not satisfied by less 2.5.0_2.
Constraints on package "less":
- less@=2.5.0_2 <- top level
- less@2.5.0_1 <- accounts-ui 1.1.6
- less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
- less@1.0.14 <- babrahams:accounts-ldap 0.3.3

**Comment by JackAdams** [comment]
Thanks for reporting. I guess you're using Meteor 1.2? I'll need to declare the dependencies explicitly to make this package compatible. New release coming out in an hour or two.

**Comment by JackAdams** [comment]
0.4.0 should solve this. `meteor update` again.

**Comment by zalewskigrzegorz** [comment]
Now works perfectly.
