### ISSUE TITLE
Exception while invoking method 'login' TypeError: Cannot read property '' of null

### ISSUE THREAD

**Issue by tdhz77** [JackAdams/meteor-accounts-ldap#7]
I'm moving from HIVE:LDAP package, where I had ldap working, but I found your package to be more for what I'm needing. 

Made one small change from the original HIVE settings.  Moved the DC to DN and removed DC line completely.

User successfully retrieved from LDAP server
...

I20150923-10:32:29.920(-5)? Exception while invoking method 'login' TypeError: Cannot read property '' of null
I20150923-10:32:29.920(-5)?     at [object Object].Package (packages/babrahams:accounts-ldap/ldap_server.js:324:1)
I20150923-10:32:29.921(-5)?     at packages/accounts-base/accounts_server.js:358:1
I20150923-10:32:29.921(-5)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:161:1)
I20150923-10:32:29.921(-5)?     at runLoginHandlers (packages/accounts-base/accounts_server.js:355:1)
I20150923-10:32:29.921(-5)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:409:1)
I20150923-10:32:29.921(-5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150923-10:32:29.922(-5)?     at packages/ddp/livedata_server.js:648:1
I20150923-10:32:29.922(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150923-10:32:29.922(-5)?     at packages/ddp/livedata_server.js:647:1
I20150923-10:32:29.922(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150923-10:32:29.922(-5)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150923-10:32:29.922(-5)?     at packages/ddp/livedata_server.js:546:1
I20150923-10:32:29.922(-5)? status: 0

Any ideas?

**Comment by tdhz77** [comment]
updating to Meteor 1.2 fixed the issue... (I believe)

**Comment by JackAdams** [comment]
This was a genuine bug in the package.  I just released 0.4.2 which fixes it.  Thanks for reporting!
