### ISSUE TITLE
Using this package in react

### ISSUE THREAD

**Issue by tdhz77** [JackAdams/meteor-accounts-ldap#9]
AccountsUIWrapper = React.createClass({
  componentDidMount() {
    // Use Meteor Blaze to render login buttons
    this.view = Blaze.render(Template.ldapLoginButtons , //changed 
      React.findDOMNode(this.refs.container));
  },
  componentWillUnmount() {
    // Clean up Blaze view
    Blaze.remove(this.view);
  },
  render() {
    // Just render a placeholder container that will be filled in
    return <span ref="container" />;
  }
});

However, I'm unable to customize the template.

I've tried passing Meteor.loginwithLDAP to the login(e) function on my login.jsx, but it goes nowhere. 
any help on this would be great!

I'm also unsure how to pass these options to a blaze.render function.
make the sign in form more configurable with options like:
unstyled=true - to remove all classes
alwaysOpen - to make the form automatically open
loggedOutLinkTemplate - to replace the default link that you click to open the form
loggedInLinkTemplate - to replace the default link that you click to get the dropdown once logged in

**Comment by JackAdams** [comment]
Sorry about the late response -- I only just now noticed you'd raised this issue.  There is a package `babrahams:accounts-ldap-ionic` that completely overwrites the default form that this package contains.  I don't know if looking at the source of that would help or not.  I haven't tried integrating this into a react app yet, so I can't offer much help right now.  It will happen one day, but it may be six months down the track before I really start using react.

**Comment by tdhz77** [comment]
I tried with meteoraccounts:core and I couldn't get it to with LDAP. So I'm going to roll out my own solution when I get the time.
